container:
  image: node:latest

check_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat EKVault/package-lock.json
  script: cd EKVault && npm i && npm run build:linux:production && npm run test:ci && npm run lint