container:
  image: node:latest

check_task:
  node_modules_cache:
    folder: Passwordmanager/node_modules
    fingerprint_script: cat Passwordmanager/package-lock.json
  script: cd Passwordmanager && npm i && npm run build:production && npm run test:ci && npm run lint