container:
  image: node:latest

check_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
  script: npm i && npm run build && npm run test:ci && npm run lint
